# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/practical-deep-learning',
                'doc_host': 'https://dan.github.io',
                'git_url': 'https://github.com/dan/practical-deep-learning',
                'lib_path': 'practical_deep_learning'},
  'syms': {'practical_deep_learning.core': {'practical_deep_learning.core.foo': ('core.html#foo', 'practical_deep_learning/core.py')}}}
